name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd /home/ubuntu/actions-runner/_work/ExamMateBE/ExamMateBE
          uv sync
          source venv/bin/activate

      - name: Restart FastAPI service
        run: |
          sudo systemctl restart fastapi.service
